spring:
  application:
    name: SE_form_backend

  datasource:
    url: jdbc:postgresql://localhost:5432/isslab
    username: isslab
    password: isslab

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO

server:
  address: 127.0.0.1
  port: 8080

admin:
  username: <admin-username>
  password: <admin-password>

jwt:
  secretKey: <your-key>

app:
  frontEnd:
    base-url: http://my-frontend.com/

csv:
  output-path:
    grades: <app-path>/backend-output/grades
    forms: <app-path>/backend-output/forms
    records: <app-path>/backend-output/records
